# Generated by Django 5.0.1 on 2024-01-22 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimetableEntries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "MONDAY"),
                            ("tuesday", "TUESDAY"),
                            ("wednessday", "WEDNESSDAY"),
                            ("thursday", "THURSDAY"),
                            ("friday", "FRIDAY"),
                            ("saturday", "SATURDAY"),
                            ("sunday", "SUNDAY"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField()),
                ("timeslot", models.CharField(max_length=50)),
                ("building", models.CharField(max_length=255)),
                ("room", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedTimetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.timetableentries",
                    ),
                ),
            ],
        ),
    ]
